//using OneCSharp.DDL.Attributes;

//namespace DaJet.CodeGenerator.CSharp
//{
//	[Entity(TableName = "MyTable")] public sealed class MyTestClass : ReferenceObject
//	{
//		[Field(Name = "MyField", TypeName = "", IsPrimaryKey = true, KeyOrdinal = 0,
//			Length = 16, IsNullable = false, Precision = 0, Scale = 0,
//			IsAutoGenerated = false, Purpose = FieldPurpose.Numeric)]
//		public string MyName { get; set; }
//	}
//}
